### ISSUE TITLE
dylib not found on macos 10.14.6

### ISSUE THREAD

**Issue by willisplummer** [cachix/ghcide-nix#38] opened 2020-02-13 02:45 UTC
```
[nix-shell:~/code/haskell-game]$ ghcide
dyld: Library not loaded: @rpath/libHSoptparse-applicative-0.14.3.0-LtaVKT3RHsp42IZXcCLerz-ghc8.6.5.dylib
  Referenced from: /nix/store/lhc3iz3gfgmsmxkyxqcaxbs8jlx9my3d-ghcide-0.1.0-exe-ghcide/bin/ghcide
  Reason: image not found
Abort trap: 6
```

wondering if this is because the cached image needs to be updated?

**Comment by n4074** [comment] 2020-02-13 12:26
I've just hit the same issue. It seems that _rpaths_ for the cached build are oddly pointing to `/opt/nix`

```
otool -l /nix/store/lhc3iz3gfgmsmxkyxqcaxbs8jlx9my3d-ghcide-0.1.0-exe-ghcide/bin/ghcide | grep 'path '
         path /opt/nix/store/lwrla99wyvr61khk3n7qwayarzaxv5nh-ghc-8.6.5/lib/ghc-8.6.5/rts (offset 12)
         path /opt/nix/store/rv6qmd9nc42qx8bvvgvlb4rf353qfbfi-libffi-3.2.1/lib (offset 12)
         path /opt/nix/store/5fc0v2aqs8k89gmq8yyi9cg5fsapj6l8-ghcide-0.1.0-exe-ghcide-config/lib/links (offset 12)
         path /nix/store/fvibf5c3q5ifkvn62gnpipxmm2dc419v-swift-corefoundation/Library/Frameworks (offset 12)
```
`ghcide` runs as expected after manually patching in the correct value.

**Comment by roberth** [comment] 2020-02-13 13:26
The Hercules CI agent behind `hercules-ci.cachix.org` builds it right.
Probably caused by lack of sandbox?

**Comment by willisplummer** [comment] 2020-02-13 16:33
@roberth what do you mean by lack of sandbox?

**Comment by roberth** [comment] 2020-02-13 16:50
I've had a look at `install-nix-action` (used here) just now and it uses a symlinked store, which explains the error.

The Hercules CI agent has a normal Nix store, so that's why it produces a correct build.

@willisplummer not sure if this counts as sandbox related, which was more of a guess anyway.

**Comment by domenkozar** [comment] 2020-02-14 01:26
Refs https://github.com/cachix/install-nix-action/issues/21

**Comment by domenkozar** [comment] 2020-03-06 19:48
This is fixed in master.

**Closed as completed by domenkozar** 2020-03-06 19:48 UTC

**Comment by willisplummer** [comment] 2020-03-09 16:24
@domenkozar i'm still running into this issue:

```
➜  personal-website-server git:(master) ./.ghcide
trace: Get `stack-sha256` with `nix-hash --base32 --type sha256 /nix/store/vzlv92sclddb618w2h39hk8rv289p64c-stack-to-nix-pkgs/`
dyld: Library not loaded: @rpath/libHSoptparse-applicative-0.14.3.0-LtaVKT3RHsp42IZXcCLerz-ghc8.6.5.dylib
  Referenced from: /nix/store/lhc3iz3gfgmsmxkyxqcaxbs8jlx9my3d-ghcide-0.1.0-exe-ghcide/bin/ghcide
  Reason: image not found
/private/var/folders/_r/8cnjswnx0l14f8tfz8pdxt5h0000gn/T/nix-shell-36612-0/rc: line 1: 37178 Abort trap: 6           ghcide --lsp
```

**Comment by domenkozar** [comment] 2020-03-09 21:06
@willisplummer could you run `otool -l /nix/store/lhc3iz3gfgmsmxkyxqcaxbs8jlx9my3d-ghcide-0.1.0-exe-ghcide`

**Comment by willisplummer** [comment] 2020-03-09 21:58
```
➜  haskell-game git:(master) ✗ otool -l /nix/store/lhc3iz3gfgmsmxkyxqcaxbs8jlx9my3d-ghcide-0.1.0-exe-ghcide
/Library/Developer/CommandLineTools/usr/bin/objdump: '/nix/store/lhc3iz3gfgmsmxkyxqcaxbs8jlx9my3d-ghcide-0.1.0-exe-ghcide': Is a directory
➜  haskell-game git:(master) ✗ otool -l /nix/store/lhc3iz3gfgmsmxkyxqcaxbs8jlx9my3d-ghcide-0.1.0-exe-ghcide/bin/ghcide
/nix/store/lhc3iz3gfgmsmxkyxqcaxbs8jlx9my3d-ghcide-0.1.0-exe-ghcide/bin/ghcide:
Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
 0xfeedfacf 16777223          3  0x80           2    36       3224 0x00200085
Load command 0
      cmd LC_SEGMENT_64
  cmdsize 72
  segname __PAGEZERO
   vmaddr 0x0000000000000000
   vmsize 0x0000000100000000
  fileoff 0
 filesize 0
  maxprot 0x00000000
 initprot 0x00000000
   nsects 0
    flags 0x0
Load command 1
      cmd LC_SEGMENT_64
  cmdsize 392
  segname __TEXT
   vmaddr 0x0000000100000000
   vmsize 0x0000000000013000
  fileoff 0
 filesize 77824
  maxprot 0x00000007
 initprot 0x00000005
   nsects 4
    flags 0x0
Section
  sectname __text
   segname __TEXT
      addr 0x0000000100001bb0
      size 0x0000000000010f97
    offset 7088
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x80000400
 reserved1 0
 reserved2 0
Section
  sectname __stubs
   segname __TEXT
      addr 0x0000000100012b48
      size 0x0000000000000012
    offset 76616
     align 2^1 (2)
    reloff 0
    nreloc 0
     flags 0x80000408
 reserved1 0 (index into indirect symbol table)
 reserved2 6 (size of stubs)
Section
  sectname __stub_helper
   segname __TEXT
      addr 0x0000000100012b5c
      size 0x000000000000002e
    offset 76636
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x80000400
 reserved1 0
 reserved2 0
Section
  sectname __cstring
   segname __TEXT
      addr 0x0000000100012b8a
      size 0x000000000000046c
    offset 76682
     align 2^1 (2)
    reloff 0
    nreloc 0
     flags 0x00000002
 reserved1 0
 reserved2 0
Load command 2
      cmd LC_SEGMENT_64
  cmdsize 392
  segname __DATA
   vmaddr 0x0000000100013000
   vmsize 0x0000000000004000
  fileoff 77824
 filesize 16384
  maxprot 0x00000007
 initprot 0x00000003
   nsects 4
    flags 0x0
Section
  sectname __got
   segname __DATA
      addr 0x0000000100013000
      size 0x0000000000000658
    offset 77824
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000006
 reserved1 3 (index into indirect symbol table)
 reserved2 0
Section
  sectname __nl_symbol_ptr
   segname __DATA
      addr 0x0000000100013658
      size 0x0000000000000010
    offset 79448
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000006
 reserved1 206 (index into indirect symbol table)
 reserved2 0
Section
  sectname __la_symbol_ptr
   segname __DATA
      addr 0x0000000100013668
      size 0x0000000000000018
    offset 79464
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000007
 reserved1 208 (index into indirect symbol table)
 reserved2 0
Section
  sectname __data
   segname __DATA
      addr 0x0000000100013680
      size 0x0000000000002ef8
    offset 79488
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Load command 3
      cmd LC_SEGMENT_64
  cmdsize 72
  segname __LINKEDIT
   vmaddr 0x0000000100017000
   vmsize 0x000000000001a000
  fileoff 94208
 filesize 105668
  maxprot 0x00000007
 initprot 0x00000001
   nsects 0
    flags 0x0
Load command 4
            cmd LC_DYLD_INFO_ONLY
        cmdsize 48
     rebase_off 94208
    rebase_size 632
       bind_off 94840
      bind_size 23832
  weak_bind_off 0
 weak_bind_size 0
  lazy_bind_off 118672
 lazy_bind_size 64
     export_off 118736
    export_size 3136
Load command 5
     cmd LC_SYMTAB
 cmdsize 24
  symoff 123008
   nsyms 1887
  stroff 154044
 strsize 45832
Load command 6
            cmd LC_DYSYMTAB
        cmdsize 80
      ilocalsym 0
      nlocalsym 1354
     iextdefsym 1354
     nextdefsym 156
      iundefsym 1510
      nundefsym 377
         tocoff 0
           ntoc 0
      modtaboff 0
        nmodtab 0
   extrefsymoff 0
    nextrefsyms 0
 indirectsymoff 153200
  nindirectsyms 211
      extreloff 0
        nextrel 0
      locreloff 0
        nlocrel 0
Load command 7
          cmd LC_LOAD_DYLINKER
      cmdsize 32
         name /usr/lib/dyld (offset 12)
Load command 8
     cmd LC_UUID
 cmdsize 24
    uuid 99A0B07A-393C-31A7-B8FB-5A3EAA63226F
Load command 9
      cmd LC_VERSION_MIN_MACOSX
  cmdsize 16
  version 10.12
      sdk 10.15
Load command 10
      cmd LC_SOURCE_VERSION
  cmdsize 16
  version 0.0
Load command 11
       cmd LC_MAIN
   cmdsize 24
  entryoff 76512
 stacksize 0
Load command 12
          cmd LC_LOAD_DYLIB
      cmdsize 112
         name /nix/store/0ikg6z03p88xir1m4q3540vvdiddqssb-Libsystem-osx-10.12.6/lib/libSystem.B.dylib (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 1226.10.1
compatibility version 1.0.0
Load command 13
          cmd LC_LOAD_DYLIB
      cmdsize 104
         name @rpath/libHSoptparse-applicative-0.14.3.0-LtaVKT3RHsp42IZXcCLerz-ghc8.6.5.dylib (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 0.0.0
compatibility version 0.0.0
Load command 14
          cmd LC_LOAD_DYLIB
      cmdsize 96
         name @rpath/libHShie-bios-0.4.0-L6zBBBp1Q5vLvLrEbnZ6bt-ghc8.6.5.dylib (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 0.0.0
compatibility version 0.0.0
Load command 15
          cmd LC_LOAD_DYLIB
      cmdsize 88
         name @rpath/libHSghcide-0.1.0-IgsnFheoUt9C72ODquFWbO-ghc8.6.5.dylib (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 0.0.0
compatibility version 0.0.0
Load command 16
          cmd LC_LOAD_DYLIB
      cmdsize 88
         name @rpath/libHSshake-0.18.5-FwkAde1KwBF2RdMH8Bg6WM-ghc8.6.5.dylib (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 0.0.0
compatibility version 0.0.0
Load command 17
          cmd LC_LOAD_DYLIB
      cmdsize 96
         name @rpath/libHShaskell-lsp-0.19.0.0-AfcazErcXk7IYk8WsOUhkZ-ghc8.6.5.dylib (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 0.0.0
compatibility version 0.0.0
Load command 18
          cmd LC_LOAD_DYLIB
      cmdsize 104
         name @rpath/libHShaskell-lsp-types-0.19.0.0-3UVKfuDImdW1EGR174fqX-ghc8.6.5.dylib (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 0.0.0
compatibility version 0.0.0
Load command 19
          cmd LC_LOAD_DYLIB
      cmdsize 88
         name @rpath/libHStext-1.2.3.1-GCSbsQArgWY8ErCWIXJbi2-ghc8.6.5.dylib (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 0.0.0
compatibility version 0.0.0
Load command 20
          cmd LC_LOAD_DYLIB
      cmdsize 96
         name @rpath/libHSghc-paths-0.1.0.12-8MhNqRZlSJXAzmVO0F6ybT-ghc8.6.5.dylib (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 0.0.0
compatibility version 0.0.0
Load command 21
          cmd LC_LOAD_DYLIB
      cmdsize 88
         name @rpath/libHSghc-8.6.5-EJczqCQztt0zzT7IjTfYb-ghc8.6.5.dylib (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 0.0.0
compatibility version 0.0.0
Load command 22
          cmd LC_LOAD_DYLIB
      cmdsize 88
         name @rpath/libHSextra-1.6.18-1fmRl3vroGtLmSrVNtghQR-ghc8.6.5.dylib (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 0.0.0
compatibility version 0.0.0
Load command 23
          cmd LC_LOAD_DYLIB
      cmdsize 96
         name @rpath/libHSdirectory-1.3.3.0-D2OFsY1RdABBAGDEO5vfQe-ghc8.6.5.dylib (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 0.0.0
compatibility version 0.0.0
Load command 24
          cmd LC_LOAD_DYLIB
      cmdsize 88
         name @rpath/libHSunix-2.7.2.2-EFqbDRNh2o0ApRVKaRnFyb-ghc8.6.5.dylib (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 0.0.0
compatibility version 0.0.0
Load command 25
          cmd LC_LOAD_DYLIB
      cmdsize 96
         name @rpath/libHSfilepath-1.4.2.1-8vpM2IXSLfHBqDAUich3wV-ghc8.6.5.dylib (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 0.0.0
compatibility version 0.0.0
Load command 26
          cmd LC_LOAD_DYLIB
      cmdsize 96
         name @rpath/libHScontainers-0.6.0.1-IIa9q2aReaQIvYbFDt930S-ghc8.6.5.dylib (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 0.0.0
compatibility version 0.0.0
Load command 27
          cmd LC_LOAD_DYLIB
      cmdsize 72
         name @rpath/libHSbase-4.12.0.0-ghc8.6.5.dylib (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 0.0.0
compatibility version 0.0.0
Load command 28
          cmd LC_LOAD_DYLIB
      cmdsize 72
         name @rpath/libHSghc-prim-0.5.3-ghc8.6.5.dylib (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 0.0.0
compatibility version 0.0.0
Load command 29
          cmd LC_LOAD_DYLIB
      cmdsize 64
         name @rpath/libHSrts_thr-ghc8.6.5.dylib (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 0.0.0
compatibility version 0.0.0
Load command 30
          cmd LC_RPATH
      cmdsize 88
         path /opt/nix/store/lwrla99wyvr61khk3n7qwayarzaxv5nh-ghc-8.6.5/lib/ghc-8.6.5/rts (offset 12)
Load command 31
          cmd LC_RPATH
      cmdsize 80
         path /opt/nix/store/rv6qmd9nc42qx8bvvgvlb4rf353qfbfi-libffi-3.2.1/lib (offset 12)
Load command 32
          cmd LC_RPATH
      cmdsize 104
         path /opt/nix/store/5fc0v2aqs8k89gmq8yyi9cg5fsapj6l8-ghcide-0.1.0-exe-ghcide-config/lib/links (offset 12)
Load command 33
          cmd LC_RPATH
      cmdsize 96
         path /nix/store/fvibf5c3q5ifkvn62gnpipxmm2dc419v-swift-corefoundation/Library/Frameworks (offset 12)
Load command 34
      cmd LC_FUNCTION_STARTS
  cmdsize 16
  dataoff 121872
 datasize 1136
Load command 35
      cmd LC_DATA_IN_CODE
  cmdsize 16
  dataoff 123008
 datasize 0
```

**Comment by domenkozar** [comment] 2020-03-10 10:34
Need to clear cachix cache, will bump ghcide soon and that should hopefully fix it.

**Comment by domenkozar** [comment] 2020-03-14 21:42
@willisplummer could you try installing ghc-ide again?

**Comment by willisplummer** [comment] 2020-03-15 00:55
@domenkozar sorry - i already cleared the cache manually by uninstalling everything and installing fresh so i can't verify if the cache bump worked, but everything is working correctly for me now. thanks for all your work answering my github issues etc!
